#! /bin/sh

# ╔════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                                                            ║
# ║   .S_sSSs     .S_SSSs     .S     S.     sSSs    sSSs    sSSs_sSSs     .S_SsS_S.     sSSs   ║
# ║  .SS~YS%%b   .SS~SSSSS   .SS     SS.   d%%SP   d%%SP   d%%SP~YS%%b   .SS~S*S~SS.   d%%SP   ║
# ║  S%S   `S%b  S%S   SSSS  S%S     S%S  d%S'    d%S'    d%S'     `S%b  S%S `Y' S%S  d%S'     ║
# ║  S%S    S%S  S%S    S%S  S%S     S%S  S%S     S%|     S%S       S%S  S%S     S%S  S%S      ║
# ║  S%S    d*S  S%S SSSS%S  S%S     S%S  S&S     S&S     S&S       S&S  S%S     S%S  S&S      ║
# ║  S&S   .S*S  S&S  SSS%S  S&S     S&S  S&S_Ss  Y&Ss    S&S       S&S  S&S     S&S  S&S_Ss   ║
# ║  S&S_sdSSS   S&S    S&S  S&S     S&S  S&S~SP  `S&&S   S&S       S&S  S&S     S&S  S&S~SP   ║
# ║  S&S~YSSY    S&S    S&S  S&S     S&S  S&S       `S*S  S&S       S&S  S&S     S&S  S&S      ║
# ║  S*S         S*S    S&S  S*S     S*S  S*b        l*S  S*b       d*S  S*S     S*S  S*b      ║
# ║  S*S         S*S    S*S  S*S  .  S*S  S*S.      .S*P  S*S.     .S*S  S*S     S*S  S*S.     ║
# ║  S*S         S*S    S*S  S*S_sSs_S*S   SSSbs  sSS*S    SSSbs_sdSSS   S*S     S*S   SSSbs   ║
# ║  S*S         SSS    S*S  SSS~SSS~S*S    YSSP  YSS'      YSSP~YSSY    SSS     S*S    YSSP   ║
# ║  SP                 SP                                                       SP            ║
# ║  Y    ARCH THEME    Y     MADE BY CHOOI    admin@redline-software.moscow     Y             ║
# ║                                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════╝

start_process() {
    local process=$1
    local command=${2:-$1}
    if [[ ! $(pgrep -x $process) ]]; then
        $command &
    fi
}

kill_process() {
    local process=$1
    local command=${2:-$1}
    if [[ $(pgrep -x $process) ]]; then
        killall -q $process
    fi
}

restart_process() {
    local process=$1
    local command=${2:-$1}

    kill_process "$process" "$command"
    start_process "$process" "$command"
}

# Compositor
restart_process "picom" "picom --daemon --realtime"

# Notifications
restart_process "dunst" "dunst"

# Polkit
if [[ ! `pidof polkitd` ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Hotkeys
pgrep -x sxhkd > /dev/null || restart_process "sxhkd"

# Firewall
restart_process "firewall-applet" "firewall-applet"

# Network Applet
restart_process "nm-applet" "nm-applet --indicator"

# Bluetooth
restart_process "blueman-applet"

# File manager daemon
restart_process "udiskie" "udiskie"
restart_process "thunar" "thunar --daemon"

# Screenshot tool
restart_process "flameshot"

# OTD
# restart_process "otd-daemon"

# Modem and SMS
if command -v modem-manager-gui &> /dev/null; then
    sudo -u $USER killall -q modem-manager-gui
    sudo -u $USER modem-manager-gui &

    while ! xwininfo -root -tree | grep -q "modem-manager-gui"; do
        sleep 0.01
    done

    xdotool search --onlyvisible --class modem-manager-gui windowquit
fi

# Clipboard
start_process "clipcatd"

# Keyboarf layout changer
#start_process "ibus-daemon" "ibus-daemon -rxRd"

# Gestures
restart_process "libinput-gestures" "libinput-gestures -c /home/$USER/.config/libinput-gestures/libinput-gestures.conf"

# Theme manager
# restart_process "xsettingsd" "xsettingsd -c /home/chooisfox/.config/bspwm/xsettingsd"

# restart_process "snixembed" "snixembed --fork"

# OTHER STUFF

# Low battery notifier
bash ~/.config/bspwm/scripts/notify_low_battery.sh &

# Copy background for lightdm
# cp ~/.config/background/mountain.png /usr/share/bspwm/background/background.png

# Set default cursor
xsetroot -cursor_name left_ptr

# Keyboard layout (US/RU)
setxkbmap -model pc104 -layout us,ru -variant qwerty -option grp:win_space_toggle

# Dex (Autostart services)
# dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &

# Restart opened widnows
#~/.config/bspwm/scripts/bspwm_session.sh -r
