#! /bin/sh

# ╔════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                                                            ║
# ║   .S_sSSs     .S_SSSs     .S     S.     sSSs    sSSs    sSSs_sSSs     .S_SsS_S.     sSSs   ║
# ║  .SS~YS%%b   .SS~SSSSS   .SS     SS.   d%%SP   d%%SP   d%%SP~YS%%b   .SS~S*S~SS.   d%%SP   ║
# ║  S%S   `S%b  S%S   SSSS  S%S     S%S  d%S'    d%S'    d%S'     `S%b  S%S `Y' S%S  d%S'     ║
# ║  S%S    S%S  S%S    S%S  S%S     S%S  S%S     S%|     S%S       S%S  S%S     S%S  S%S      ║
# ║  S%S    d*S  S%S SSSS%S  S%S     S%S  S&S     S&S     S&S       S&S  S%S     S%S  S&S      ║
# ║  S&S   .S*S  S&S  SSS%S  S&S     S&S  S&S_Ss  Y&Ss    S&S       S&S  S&S     S&S  S&S_Ss   ║
# ║  S&S_sdSSS   S&S    S&S  S&S     S&S  S&S~SP  `S&&S   S&S       S&S  S&S     S&S  S&S~SP   ║
# ║  S&S~YSSY    S&S    S&S  S&S     S&S  S&S       `S*S  S&S       S&S  S&S     S&S  S&S      ║
# ║  S*S         S*S    S&S  S*S     S*S  S*b        l*S  S*b       d*S  S*S     S*S  S*b      ║
# ║  S*S         S*S    S*S  S*S  .  S*S  S*S.      .S*P  S*S.     .S*S  S*S     S*S  S*S.     ║
# ║  S*S         S*S    S*S  S*S_sSs_S*S   SSSbs  sSS*S    SSSbs_sdSSS   S*S     S*S   SSSbs   ║
# ║  S*S         SSS    S*S  SSS~SSS~S*S    YSSP  YSS'      YSSP~YSSY    SSS     S*S    YSSP   ║
# ║  SP                 SP                                                       SP            ║
# ║  Y    ARCH THEME    Y     MADE BY CHOOI    admin@redline-software.moscow     Y             ║
# ║                                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════╝

# Function to kill and restart processes
restart_process() {
    local process=$1
    local command=${2:-$1}  # If no second argument, use the first as the command
    killall -q "$process"
    "$command" &
}

# Polkit
restart_process "polkit-gnome-authentication-agent-1" "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"

# Hotkeys
pgrep -x sxhkd > /dev/null || restart_process "sxhkd"

# Compositor
restart_process "picom" "picom --daemon --replace"

# Notifications
restart_process "dunst"

# Network Applet
restart_process "nm-applet" "nm-applet --indicator"

# Bluetooth
killall firewall-applet
restart_process "blueman-applet"

# File manager daemon
restart_process "thunar" "thunar --daemon"

# Screenshot tool
restart_process "flameshot"

# Clipmenu
restart_process "clipmenud"

# OTD (on-the-desk daemon)
restart_process "otd-daemon"

# Gestures
restart_process "libinput-gestures" "libinput-gestures -c ~/.config/libinput-gestures/libinput-gestures.conf"

# Theme manager
restart_process "xsettingsd"

# OTHER STUFF

# Low battery notifier
bash ~/.config/bspwm/scripts/notify_low_battery.sh &

# Copy background for lightdm
# cp ~/.config/background/mountain.png /usr/share/bspwm/background/background.png

# Set default cursor
xsetroot -cursor_name left_ptr

# Keyboard layout (US/RU)
setxkbmap -model pc104 -layout us,ru -variant qwerty -option grp:win_space_toggle

# Dex (Autostart services)
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
