#! /bin/sh

# ╔════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                                                            ║
# ║   .S_sSSs     .S_SSSs     .S     S.     sSSs    sSSs    sSSs_sSSs     .S_SsS_S.     sSSs   ║
# ║  .SS~YS%%b   .SS~SSSSS   .SS     SS.   d%%SP   d%%SP   d%%SP~YS%%b   .SS~S*S~SS.   d%%SP   ║
# ║  S%S   `S%b  S%S   SSSS  S%S     S%S  d%S'    d%S'    d%S'     `S%b  S%S `Y' S%S  d%S'     ║
# ║  S%S    S%S  S%S    S%S  S%S     S%S  S%S     S%|     S%S       S%S  S%S     S%S  S%S      ║
# ║  S%S    d*S  S%S SSSS%S  S%S     S%S  S&S     S&S     S&S       S&S  S%S     S%S  S&S      ║
# ║  S&S   .S*S  S&S  SSS%S  S&S     S&S  S&S_Ss  Y&Ss    S&S       S&S  S&S     S&S  S&S_Ss   ║
# ║  S&S_sdSSS   S&S    S&S  S&S     S&S  S&S~SP  `S&&S   S&S       S&S  S&S     S&S  S&S~SP   ║
# ║  S&S~YSSY    S&S    S&S  S&S     S&S  S&S       `S*S  S&S       S&S  S&S     S&S  S&S      ║
# ║  S*S         S*S    S&S  S*S     S*S  S*b        l*S  S*b       d*S  S*S     S*S  S*b      ║
# ║  S*S         S*S    S*S  S*S  .  S*S  S*S.      .S*P  S*S.     .S*S  S*S     S*S  S*S.     ║
# ║  S*S         S*S    S*S  S*S_sSs_S*S   SSSbs  sSS*S    SSSbs_sdSSS   S*S     S*S   SSSbs   ║
# ║  S*S         SSS    S*S  SSS~SSS~S*S    YSSP  YSS'      YSSP~YSSY    SSS     S*S    YSSP   ║
# ║  SP                 SP                                                       SP            ║
# ║  Y    ARCH THEME    Y     MADE BY CHOOI    admin@redline-software.moscow     Y             ║
# ║                                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════╝

# Functions 
setup_desktop() {
    local desktop_number=$1; shift
    local app_name=("$@")
    for i in ${app_name[@]}; do
		bspc rule -a '$i' desktop='^$desktop_number' follow=on focus=on; done
}

# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Setup default monitor settings
#                 1    2    3    4    5    6    7    8    9   10
bspc monitor -d TERM MERG CODE WEBM EDIT MPTY CHAT LATX MUSI MISC

# Border settings
bspc config border_width          0
bspc config window_gap            12

# Border colors 
bspc config focused_border_color        "#e6ac0c"
bspc config normal_border_color         "#e6ac0c"
bspc config active_border_color         "#e6ac0c"

# Window positioning
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Desktops apps
declare -a terminal=()
declare -a main_git=(Sublime\ Merge Sublime_merge sublime_merge smerge)
declare -a main_editor=(Sublime\ Text Sublime_text sublime_text subl nvim vim)
declare -a browser=(firefox)
declare -a secondary_editor=(qtcreator)
declare -a empty=()
declare -a chat=(telegram-desktop)
declare -a latex=(libreoffice-writer libreoffice-calc libreoffice-impress libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
declare -a music=(cmus)
declare -a misc=(htop)

# Desktop setup
setup_desktop 1  "${terminal[@]}"
setup_desktop 2  "${main_git[@]}"
setup_desktop 3  "${main_editor[@]}"
setup_desktop 4  "${browser[@]}"
setup_desktop 5  "${secondary_editor[@]}"
setup_desktop 6  "${empty[@]}"
setup_desktop 7  "${chat[@]}"
setup_desktop 8  "${latex[@]}"
setup_desktop 9  "${music[@]}"
setup_desktop 10 "${misc[@]}"

# Floating Apps
declare -a floatingApps=(dolphin Dolphin URxvt alacritty Alacritty xterm xfce xfce4 Xfce4-terminal xfce4-terminal xdman-Main Lxappearance Gparted Thunar \
Viewnior Xarchiver Pavucontrol firefox:Dialog firefox:Browser \
firefox:Pop-up nitrogen Gpick)
for i in ${floatingApps[@]}; do
    bspc rule -a $i state=floating focus=on follow=on\
    rectangle=800x600+560+240; done

# Floating media
declare -a floatingCust=(*:*:Picture-in-picture *:Toolkit:Picture-in-Picture mpv)
for i in ${floatingCust[@]}; do
    bspc rule -a $i state=floating sticky=on follow=off focus=on \
    rectangle=500x300+1366+50; done

# Start screen 
bspc rule -a cava state=floating desktop='^1' focus=on follow=off rectangle=600x200+10+40;

# Load autostart script
~/.config/bspwm/autostart
